### ISSUE TITLE
Duplicate segment ids in panoptic annotations

### ISSUE THREAD

**Issue by SamedYalcin** [lojzezust/lars_evaluator#1]
There are duplicate segment ids in panoptic_annotations.json. Here's how I check:

```
f = open(r"F:\Datasets\lars_v1.0.0_annotations\train\panoptic_annotations.json", "r")
import json
j = json.load(f)
anns = j["annotations"]
ids = list()
 for ann in anns:
   for seg in ann["segments_info"]:
      ids.append(seg["id"])
sids = set(ids)
len(ids)
> 16951
len(sids)
> 602
```

According to COCO annotation style, segments ids must be unique, if I'm understanding correctly. Can you check please?

**Comment by lojzezust** [comment]
According to the [COCO format](https://cocodataset.org/#format-data), the segment IDs are used to retrieve corresponding masks from the panoptic PNG files. Therefore they only need to be unique on a **per-image** basis. Otherwise, we would quickly run out of unique IDs for larger datasets.

You can check that IDs are unique per-image in LaRS using the following code:

```python
import json

with open(r"F:\Datasets\lars_v1.0.0_annotations\train\panoptic_annotations.json", 'r') as file:
    data = json.load(file)

for i,ann in enumerate(data['annotations']):
    ids = [s['id'] for s in ann['segments_info']]
    # Check if IDs are unique
    if len(ids) != len(set(ids)):
        print("Duplicate found:", i, ann['file_name'])
```
